Repository yt-project/unyt, pull requests merged in 2024-10, with the labels that each got.

#521 add foe and Bethe units
  unyt/_physical_ratios.py
  unyt/_unit_lookup_table.py
Labels: enhancement

#520 Fix Stephan-Boltzmann constant accuracy and add radiation constant
  unyt/_physical_ratios.py
  unyt/_unit_lookup_table.py
  unyt/equivalencies.py
Labels: bug, enhancement

#531 BUG: fix return units from numpy.ftt functions
  unyt/_array_functions.py
  unyt/tests/test_array_functions.py
Labels: bug
